name: sistema_advocacia
description: Sistema de gerenciamento para advogados
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8
  sqflite_common_ffi: ^2.3.3
  path: ^1.8.3
  file_picker: ^8.0.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
